config/routes.rb
Rails.application.routes.draw do
  root "flights#index"

  devise_for :users

  resources :flights, only: [:index, :show]
  resources :bookings, only: [:new, :create, :show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :code, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :user
  has_many :passengers, inverse_of: :booking, dependent: :destroy

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport", foreign_key: "departure_airport_id"
  belongs_to :arrival_airport, class_name: "Airport", foreign_key: "arrival_airport_id"

  has_many :bookings
  has_many :users, through: :bookings, class_name: "User"

  def self.filter_by_departure_airport(airport_id)
    where(departure_airport_id: airport_id)
  end

  def self.filter_by_arrival_airport(airport_id)
    where(arrival_airport_id: airport_id)
  end

  def self.filter_by_passangers(passanger_count)
    where(passanger_count: passanger_count)
  end

  def self.filter_by_date(date)
    where(start_datetime: date.beginning_of_day..date.end_of_day)
  end
end

app/models/flight_search.rb
class FlightSearch
  include ActiveModel::Model

  attr_accessor :departure_airport, :arrival_airport, :passenger_count, :flight_date

  def flight_date_datetime
    flight_date.to_datetime if flight_date.present?
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking, class_name: "Booking"

  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :flights, through: :bookings, class_name: "Flight"
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flight, only: [:new, :create]

  def new
    @passenger_count = params[:booking][:num_passengers].to_i || 1
    @booking = Booking.new(flight: @flight, user: current_user, num_passengers: @passenger_count)
    @booking.user = current_user
    @passenger = @booking.num_passengers.to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.flight = @flight
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def set_flight
    @flight = Flight.find_by(id: params[:booking][:flight_id])
    if @flight.nil?
      flash[:error] = "Flight not found"
      redirect_to flights_path
    end
  end

  def booking_params
    params.require(:booking).permit(:flight_id, :num_passengers, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_search_flag, only: :index

  def index
    @booking = Booking.new
    @flight_search = FlightSearch.new(flight_search_params)
    @flights = Flight.all
    @flights = Flight.filter_by_departure_airport(@flight_search.departure_airport) if @flight_search.departure_airport.present?
    @flights = Flight.filter_by_arrival_airport(@flight_search.arrival_airport) if @flight_search.arrival_airport.present?
    @flights = Flight.filter_by_date(@flight_search.flight_date_datetime) if @flight_search.flight_date.present?
  end

  def show
    @flight = Flight.find(params[:id])
  end

  private

  def flight_search_params
    params.fetch(:flight_search, {}).permit(:departure_airport, :arrival_airport, :passenger_count, :flight_date)
  end

  def set_search_flag
    @search_performed = params[:flight_search].present?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @airport = Airport.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def format_datetime(datetime)
    datetime.strftime("%B %d, %Y, %I:%M %p")
  end
end

app/views/bookings/new.html.erb
<%= simple_form_for @booking, url: bookings_path, method: :post do |f| %>
  <p>Selected Flight: <%= @flight.start_datetime %> - <%= @flight.departure_airport.name %> to <%= @flight.arrival_airport.name %></p>
  <% passenger_count = @passenger_count || 1 %>
  <%= f.hidden_field :flight_id, value: @flight.id %>
  <%= f.input :num_passengers, as: :hidden, input_html: { value: passenger_count } %>
  <%= f.fields_for :passengers do |passenger_fields| %>
    <div class="passenger-fields">
      <%= passenger_fields.label :name, "Passenger Name" %>
      <%= passenger_fields.text_field :name %>
      <%= passenger_fields.label :email, "Passenger Email" %>
      <%= passenger_fields.email_field :email %>
    </div>
  <% end %>
  <%= f.button :submit, 'Continue to Booking' %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Information</h1>
<p>Flight: <%= @booking.flight.start_datetime %> - <%= @booking.flight.departure_airport.name %> to <%= @booking.flight.arrival_airport.name %></p>
<p>Number of Passengers: <%= @booking.num_passengers %></p>
<h2>Passengers:</h2>
<ul>
  <% @booking.passengers.each do |passenger| %>
    <li><strong>Name:</strong> <%= passenger.name %></li>
    <li><strong>Email:</strong> <%= passenger.email %></li>
  <% end %>
</ul>

app/views/flights/index.html.erb
<% if current_user %>
  <p> Logged in as <%= current_user.email %></p>
  <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>
<h1>Flight Search</h1>
<%= simple_form_for :flight_search, url: flights_path, method: :get do |f| %>
  <div class="form-inputs">
    <%= f.input :departure_airport, collection: Airport.all, label: "Departure Airport", include_blank: "Select Departure Airport" %>
    <%= f.input :arrival_airport, collection: Airport.all, label: "Arrival Airport", include_blank: "Select Arrival Airport" %>
    <%= f.input :passenger_count, collection: 1..4, label: "Number of Passengers", include_blank: false, input_html: { value: 1 } %>
    <%= f.input :flight_date, collection: Flight.select(:start_datetime).distinct.pluck(:start_datetime).map(&:to_date), as: :select, label: "Flight Date", include_blank: "Select Flight Date" %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Search Flights" %>
  </div>
<% end %>
<% if @search_performed %>
  <%= simple_form_for @booking, url: new_booking_path, method: :get do |f| %>
    <% @flights.each do |flight| %>
      <%= f.radio_button :flight_id, flight.id %>
      <%= flight.start_datetime %> - <%= flight.departure_airport.name %> to <%= flight.arrival_airport.name %>
      <br>
    <% end %>
    <%= f.input_field :num_passengers, value: params.dig(:flight_search, :passenger_count), as: :hidden %>
    <%= f.button :submit, 'Select Flight' %>
  <% end %>
<% else %>
  <p>Please perform a flight search first to select a flight.</p>
<% end %>

app/views/flights/show.html.erb
flight

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% if current_user %>
  <p> Logged in as <%= current_user.email %></p>
  <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>
<%= @airport.name %>

app/views/pages/pages.html.erb
<% if current_user %>
  <p> Logged in as <%= current_user.email %></p>
  <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>